apiVersion: v1
kind: Service
metadata:
  name: jupyter-svc
spec:
  type: NodePort
  selector:
    app: jupyter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: notebook
          image: jupyter-yolo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          env:
            - name: JUPYTER_TOKEN
              value: "1234"
          resources:
            limits:
              nvidia.com/gpu.shared: 1
          volumeMounts:
            - name: workdir
              mountPath: /home/user/work
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: "project"