// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/audit.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	audit "github.com/linskybing/platform-go/internal/domain/audit"
	repository "github.com/linskybing/platform-go/internal/repository"
)

// MockAuditRepo is a mock of AuditRepo interface.
type MockAuditRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepoMockRecorder
}

// MockAuditRepoMockRecorder is the mock recorder for MockAuditRepo.
type MockAuditRepoMockRecorder struct {
	mock *MockAuditRepo
}

// NewMockAuditRepo creates a new mock instance.
func NewMockAuditRepo(ctrl *gomock.Controller) *MockAuditRepo {
	mock := &MockAuditRepo{ctrl: ctrl}
	mock.recorder = &MockAuditRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepo) EXPECT() *MockAuditRepoMockRecorder {
	return m.recorder
}

// CreateAuditLog mocks base method.
func (m *MockAuditRepo) CreateAuditLog(audit *audit.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuditLog", audit)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAuditLog indicates an expected call of CreateAuditLog.
func (mr *MockAuditRepoMockRecorder) CreateAuditLog(audit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuditLog", reflect.TypeOf((*MockAuditRepo)(nil).CreateAuditLog), audit)
}

// GetAuditLogs mocks base method.
func (m *MockAuditRepo) GetAuditLogs(params repository.AuditQueryParams) ([]audit.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditLogs", params)
	ret0, _ := ret[0].([]audit.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditLogs indicates an expected call of GetAuditLogs.
func (mr *MockAuditRepoMockRecorder) GetAuditLogs(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditLogs", reflect.TypeOf((*MockAuditRepo)(nil).GetAuditLogs), params)
}

// DeleteOldAuditLogs mocks base method.
func (m *MockAuditRepo) DeleteOldAuditLogs(retentionDays int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldAuditLogs", retentionDays)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOldAuditLogs indicates an expected call of DeleteOldAuditLogs.
func (mr *MockAuditRepoMockRecorder) DeleteOldAuditLogs(retentionDays interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldAuditLogs", reflect.TypeOf((*MockAuditRepo)(nil).DeleteOldAuditLogs), retentionDays)
}
