// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/project.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	project "github.com/linskybing/platform-go/internal/domain/project"
	view "github.com/linskybing/platform-go/internal/domain/view"
	repository "github.com/linskybing/platform-go/internal/repository"
	"gorm.io/gorm"
)

// MockProjectRepo is a mock of ProjectRepo interface.
type MockProjectRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepoMockRecorder
}

// MockProjectRepoMockRecorder is the mock recorder for MockProjectRepo.
type MockProjectRepoMockRecorder struct {
	mock *MockProjectRepo
}

// NewMockProjectRepo creates a new mock instance.
func NewMockProjectRepo(ctrl *gomock.Controller) *MockProjectRepo {
	mock := &MockProjectRepo{ctrl: ctrl}
	mock.recorder = &MockProjectRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepo) EXPECT() *MockProjectRepoMockRecorder {
	return m.recorder
}

// CreateProject mocks base method.
func (m *MockProjectRepo) CreateProject(p *project.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockProjectRepoMockRecorder) CreateProject(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockProjectRepo)(nil).CreateProject), p)
}

// DeleteProject mocks base method.
func (m *MockProjectRepo) DeleteProject(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockProjectRepoMockRecorder) DeleteProject(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockProjectRepo)(nil).DeleteProject), id)
}

// GetGroupIDByProjectID mocks base method.
func (m *MockProjectRepo) GetGroupIDByProjectID(pID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupIDByProjectID", pID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupIDByProjectID indicates an expected call of GetGroupIDByProjectID.
func (mr *MockProjectRepoMockRecorder) GetGroupIDByProjectID(pID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupIDByProjectID", reflect.TypeOf((*MockProjectRepo)(nil).GetGroupIDByProjectID), pID)
}

// GetProjectByID mocks base method.
func (m *MockProjectRepo) GetProjectByID(id uint) (project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByID", id)
	ret0, _ := ret[0].(project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByID indicates an expected call of GetProjectByID.
func (mr *MockProjectRepoMockRecorder) GetProjectByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByID", reflect.TypeOf((*MockProjectRepo)(nil).GetProjectByID), id)
}

// ListProjects mocks base method.
func (m *MockProjectRepo) ListProjects() ([]project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects")
	ret0, _ := ret[0].([]project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockProjectRepoMockRecorder) ListProjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockProjectRepo)(nil).ListProjects))
}

// ListProjectsByGroup mocks base method.
func (m *MockProjectRepo) ListProjectsByGroup(id uint) ([]project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByGroup", id)
	ret0, _ := ret[0].([]project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByGroup indicates an expected call of ListProjectsByGroup.
func (mr *MockProjectRepoMockRecorder) ListProjectsByGroup(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByGroup", reflect.TypeOf((*MockProjectRepo)(nil).ListProjectsByGroup), id)
}

// UpdateProject mocks base method.
func (m *MockProjectRepo) UpdateProject(p *project.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProject", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockProjectRepoMockRecorder) UpdateProject(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockProjectRepo)(nil).UpdateProject), p)
}

// GetAllProjectGroupViews mocks base method.
func (m *MockProjectRepo) GetAllProjectGroupViews() ([]view.ProjectGroupView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProjectGroupViews")
	ret0, _ := ret[0].([]view.ProjectGroupView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProjectGroupViews indicates an expected call of GetAllProjectGroupViews.
func (mr *MockProjectRepoMockRecorder) GetAllProjectGroupViews() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProjectGroupViews", reflect.TypeOf((*MockProjectRepo)(nil).GetAllProjectGroupViews))
}

// WithTx mocks base method.
func (m *MockProjectRepo) WithTx(tx *gorm.DB) repository.ProjectRepo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.ProjectRepo)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockProjectRepoMockRecorder) WithTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockProjectRepo)(nil).WithTx), tx)
}

// ListProjectsByUserID mocks base method.
func (m *MockProjectRepo) ListProjectsByUserID(userID uint) ([]view.ProjectUserView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByUserID", userID)
	ret0, _ := ret[0].([]view.ProjectUserView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByUserID indicates an expected call of ListProjectsByUserID.
func (mr *MockProjectRepoMockRecorder) ListProjectsByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByUserID", reflect.TypeOf((*MockProjectRepo)(nil).ListProjectsByUserID), userID)
}
