// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/user.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	user "github.com/linskybing/platform-go/internal/domain/user"
	view "github.com/linskybing/platform-go/internal/domain/view"
	repository "github.com/linskybing/platform-go/internal/repository"
	"gorm.io/gorm"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// DeleteUser mocks base method.
func (m *MockUserRepo) DeleteUser(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserRepoMockRecorder) DeleteUser(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserRepo)(nil).DeleteUser), id)
}

// GetAllUsers mocks base method.
func (m *MockUserRepo) GetAllUsers() ([]user.UserWithSuperAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers")
	ret0, _ := ret[0].([]user.UserWithSuperAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockUserRepoMockRecorder) GetAllUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockUserRepo)(nil).GetAllUsers))
}

// GetUserByID mocks base method.
func (m *MockUserRepo) GetUserByID(id uint) (user.UserWithSuperAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", id)
	ret0, _ := ret[0].(user.UserWithSuperAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepoMockRecorder) GetUserByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepo)(nil).GetUserByID), id)
}

// GetUserByUsername mocks base method.
func (m *MockUserRepo) GetUserByUsername(username string) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", username)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUserRepoMockRecorder) GetUserByUsername(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUserRepo)(nil).GetUserByUsername), username)
}

// GetUserRawByID mocks base method.
func (m *MockUserRepo) GetUserRawByID(id uint) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRawByID", id)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRawByID indicates an expected call of GetUserRawByID.
func (mr *MockUserRepoMockRecorder) GetUserRawByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRawByID", reflect.TypeOf((*MockUserRepo)(nil).GetUserRawByID), id)
}

// GetUsernameByID mocks base method.
func (m *MockUserRepo) GetUsernameByID(id uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsernameByID", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsernameByID indicates an expected call of GetUsernameByID.
func (mr *MockUserRepoMockRecorder) GetUsernameByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsernameByID", reflect.TypeOf((*MockUserRepo)(nil).GetUsernameByID), id)
}

// ListUsersPaging mocks base method.
func (m *MockUserRepo) ListUsersPaging(page, limit int) ([]user.UserWithSuperAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersPaging", page, limit)
	ret0, _ := ret[0].([]user.UserWithSuperAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersPaging indicates an expected call of ListUsersPaging.
func (mr *MockUserRepoMockRecorder) ListUsersPaging(page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersPaging", reflect.TypeOf((*MockUserRepo)(nil).ListUsersPaging), page, limit)
}

// SaveUser mocks base method.
func (m *MockUserRepo) SaveUser(user *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockUserRepoMockRecorder) SaveUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockUserRepo)(nil).SaveUser), user)
}

// ListUsersByProjectID mocks base method.
func (m *MockUserRepo) ListUsersByProjectID(projectID uint) ([]view.ProjectUserView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersByProjectID", projectID)
	ret0, _ := ret[0].([]view.ProjectUserView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersByProjectID indicates an expected call of ListUsersByProjectID.
func (mr *MockUserRepoMockRecorder) ListUsersByProjectID(projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersByProjectID", reflect.TypeOf((*MockUserRepo)(nil).ListUsersByProjectID), projectID)
}

// WithTx mocks base method.
func (m *MockUserRepo) WithTx(tx *gorm.DB) repository.UserRepo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.UserRepo)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockUserRepoMockRecorder) WithTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockUserRepo)(nil).WithTx), tx)
}
