// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/usergroup.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	group "github.com/linskybing/platform-go/internal/domain/group"
	repository "github.com/linskybing/platform-go/internal/repository"
	"gorm.io/gorm"
)

// MockUserGroupRepo is a mock of UserGroupRepo interface.
type MockUserGroupRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserGroupRepoMockRecorder
}

// MockUserGroupRepoMockRecorder is the mock recorder for MockUserGroupRepo.
type MockUserGroupRepoMockRecorder struct {
	mock *MockUserGroupRepo
}

// NewMockUserGroupRepo creates a new mock instance.
func NewMockUserGroupRepo(ctrl *gomock.Controller) *MockUserGroupRepo {
	mock := &MockUserGroupRepo{ctrl: ctrl}
	mock.recorder = &MockUserGroupRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserGroupRepo) EXPECT() *MockUserGroupRepoMockRecorder {
	return m.recorder
}

// CreateUserGroup mocks base method.
func (m *MockUserGroupRepo) CreateUserGroup(userGroup *group.UserGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserGroup", userGroup)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserGroup indicates an expected call of CreateUserGroup.
func (mr *MockUserGroupRepoMockRecorder) CreateUserGroup(userGroup interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserGroup", reflect.TypeOf((*MockUserGroupRepo)(nil).CreateUserGroup), userGroup)
}

// UpdateUserGroup mocks base method.
func (m *MockUserGroupRepo) UpdateUserGroup(userGroup *group.UserGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserGroup", userGroup)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserGroup indicates an expected call of UpdateUserGroup.
func (mr *MockUserGroupRepoMockRecorder) UpdateUserGroup(userGroup interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserGroup", reflect.TypeOf((*MockUserGroupRepo)(nil).UpdateUserGroup), userGroup)
}

// DeleteUserGroup mocks base method.
func (m *MockUserGroupRepo) DeleteUserGroup(uid, gid uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserGroup", uid, gid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserGroup indicates an expected call of DeleteUserGroup.
func (mr *MockUserGroupRepoMockRecorder) DeleteUserGroup(uid, gid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserGroup", reflect.TypeOf((*MockUserGroupRepo)(nil).DeleteUserGroup), uid, gid)
}

// GetUserGroupsByUID mocks base method.
func (m *MockUserGroupRepo) GetUserGroupsByUID(uid uint) ([]group.UserGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserGroupsByUID", uid)
	ret0, _ := ret[0].([]group.UserGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserGroupsByUID indicates an expected call of GetUserGroupsByUID.
func (mr *MockUserGroupRepoMockRecorder) GetUserGroupsByUID(uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserGroupsByUID", reflect.TypeOf((*MockUserGroupRepo)(nil).GetUserGroupsByUID), uid)
}

// GetUserGroupsByGID mocks base method.
func (m *MockUserGroupRepo) GetUserGroupsByGID(gid uint) ([]group.UserGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserGroupsByGID", gid)
	ret0, _ := ret[0].([]group.UserGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserGroupsByGID indicates an expected call of GetUserGroupsByGID.
func (mr *MockUserGroupRepoMockRecorder) GetUserGroupsByGID(gid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserGroupsByGID", reflect.TypeOf((*MockUserGroupRepo)(nil).GetUserGroupsByGID), gid)
}

// GetUserGroup mocks base method.
func (m *MockUserGroupRepo) GetUserGroup(uid, gid uint) (group.UserGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserGroup", uid, gid)
	ret0, _ := ret[0].(group.UserGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserGroup indicates an expected call of GetUserGroup.
func (mr *MockUserGroupRepoMockRecorder) GetUserGroup(uid, gid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserGroup", reflect.TypeOf((*MockUserGroupRepo)(nil).GetUserGroup), uid, gid)
}

// GetUserRoleInGroup mocks base method.
func (m *MockUserGroupRepo) GetUserRoleInGroup(uid uint, gid uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoleInGroup", uid, gid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoleInGroup indicates an expected call of GetUserRoleInGroup.
func (mr *MockUserGroupRepoMockRecorder) GetUserRoleInGroup(uid, gid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoleInGroup", reflect.TypeOf((*MockUserGroupRepo)(nil).GetUserRoleInGroup), uid, gid)
}

// WithTx mocks base method.
func (m *MockUserGroupRepo) WithTx(tx *gorm.DB) repository.UserGroupRepo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.UserGroupRepo)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockUserGroupRepoMockRecorder) WithTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockUserGroupRepo)(nil).WithTx), tx)
}

// IsSuperAdmin mocks base method.
func (m *MockUserGroupRepo) IsSuperAdmin(uid uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSuperAdmin", uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSuperAdmin indicates an expected call of IsSuperAdmin.
func (mr *MockUserGroupRepoMockRecorder) IsSuperAdmin(uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSuperAdmin", reflect.TypeOf((*MockUserGroupRepo)(nil).IsSuperAdmin), uid)
}
