apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server-deploy
  labels:
    app: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: "master.harbor.registry/docker-hub/codercom/code-server:latest"
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PASSWORD
          value: "1234"
        volumeMounts:
          - name: workdir
            mountPath: /home/coder
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: project
---
apiVersion: v1
kind: Service
metadata:
  name: code-server-svc
spec:
  type: NodePort
  selector:
    app: code-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
