// Code generated by MockGen. DO NOT EDIT.
// Source: ./repositories/view_repository.go

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/linskybing/platform-go/src/models"
)

// MockViewRepo is a mock of ViewRepo interface.
type MockViewRepo struct {
	ctrl     *gomock.Controller
	recorder *MockViewRepoMockRecorder
}

// MockViewRepoMockRecorder is the mock recorder for MockViewRepo.
type MockViewRepoMockRecorder struct {
	mock *MockViewRepo
}

// NewMockViewRepo creates a new mock instance.
func NewMockViewRepo(ctrl *gomock.Controller) *MockViewRepo {
	mock := &MockViewRepo{ctrl: ctrl}
	mock.recorder = &MockViewRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockViewRepo) EXPECT() *MockViewRepoMockRecorder {
	return m.recorder
}

// GetAllProjectGroupViews mocks base method.
func (m *MockViewRepo) GetAllProjectGroupViews() ([]models.ProjectGroupView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProjectGroupViews")
	ret0, _ := ret[0].([]models.ProjectGroupView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProjectGroupViews indicates an expected call of GetAllProjectGroupViews.
func (mr *MockViewRepoMockRecorder) GetAllProjectGroupViews() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProjectGroupViews", reflect.TypeOf((*MockViewRepo)(nil).GetAllProjectGroupViews))
}

// GetGroupIDByConfigFileID mocks base method.
func (m *MockViewRepo) GetGroupIDByConfigFileID(cfID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupIDByConfigFileID", cfID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupIDByConfigFileID indicates an expected call of GetGroupIDByConfigFileID.
func (mr *MockViewRepoMockRecorder) GetGroupIDByConfigFileID(cfID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupIDByConfigFileID", reflect.TypeOf((*MockViewRepo)(nil).GetGroupIDByConfigFileID), cfID)
}

// GetGroupIDByResourceID mocks base method.
func (m *MockViewRepo) GetGroupIDByResourceID(rID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupIDByResourceID", rID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupIDByResourceID indicates an expected call of GetGroupIDByResourceID.
func (mr *MockViewRepoMockRecorder) GetGroupIDByResourceID(rID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupIDByResourceID", reflect.TypeOf((*MockViewRepo)(nil).GetGroupIDByResourceID), rID)
}

// GetGroupResourcesByGroupID mocks base method.
func (m *MockViewRepo) GetGroupResourcesByGroupID(groupID uint) ([]models.GroupResourceView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupResourcesByGroupID", groupID)
	ret0, _ := ret[0].([]models.GroupResourceView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupResourcesByGroupID indicates an expected call of GetGroupResourcesByGroupID.
func (mr *MockViewRepoMockRecorder) GetGroupResourcesByGroupID(groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupResourcesByGroupID", reflect.TypeOf((*MockViewRepo)(nil).GetGroupResourcesByGroupID), groupID)
}

// GetProjectResourcesByGroupID mocks base method.
func (m *MockViewRepo) GetProjectResourcesByGroupID(groupID uint) ([]models.ProjectResourceView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectResourcesByGroupID", groupID)
	ret0, _ := ret[0].([]models.ProjectResourceView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectResourcesByGroupID indicates an expected call of GetProjectResourcesByGroupID.
func (mr *MockViewRepoMockRecorder) GetProjectResourcesByGroupID(groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectResourcesByGroupID", reflect.TypeOf((*MockViewRepo)(nil).GetProjectResourcesByGroupID), groupID)
}

// IsSuperAdmin mocks base method.
func (m *MockViewRepo) IsSuperAdmin(uid uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSuperAdmin", uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSuperAdmin indicates an expected call of IsSuperAdmin.
func (mr *MockViewRepoMockRecorder) IsSuperAdmin(uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSuperAdmin", reflect.TypeOf((*MockViewRepo)(nil).IsSuperAdmin), uid)
}

// ListProjectsByUserID mocks base method.
func (m *MockViewRepo) ListProjectsByUserID(userID uint) ([]models.ProjectUserView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsByUserID", userID)
	ret0, _ := ret[0].([]models.ProjectUserView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsByUserID indicates an expected call of ListProjectsByUserID.
func (mr *MockViewRepoMockRecorder) ListProjectsByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsByUserID", reflect.TypeOf((*MockViewRepo)(nil).ListProjectsByUserID), userID)
}

// ListUsersByProjectID mocks base method.
func (m *MockViewRepo) ListUsersByProjectID(projectID uint) ([]models.ProjectUserView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersByProjectID", projectID)
	ret0, _ := ret[0].([]models.ProjectUserView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersByProjectID indicates an expected call of ListUsersByProjectID.
func (mr *MockViewRepoMockRecorder) ListUsersByProjectID(projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersByProjectID", reflect.TypeOf((*MockViewRepo)(nil).ListUsersByProjectID), projectID)
}

// GetUserRoleInGroup mocks base method.
func (m *MockViewRepo) GetUserRoleInGroup(uid uint, gid uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoleInGroup", uid, gid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoleInGroup indicates an expected call of GetUserRoleInGroup.
func (mr *MockViewRepoMockRecorder) GetUserRoleInGroup(uid interface{}, gid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoleInGroup", reflect.TypeOf((*MockViewRepo)(nil).GetUserRoleInGroup), uid, gid)
}
